# Generated by Django 2.1.1 on 2018-10-02 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tipjar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipjar',
            name='text',
        ),
        migrations.AddField(
            model_name='tipjar',
            name='basepair',
            field=models.CharField(default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipjar',
            name='tipjar',
            field=models.CharField(default='timezone.now', max_length=50),
            preserve_default=False,
        ),
    ]
