# Generated by Django 2.1.1 on 2018-09-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='link',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='link',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
