# Generated by Django 2.1.1 on 2018-10-05 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('body', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('sub_feed', models.TextField()),
                ('Main_Pair', models.TextField(max_length=4)),
                ('Altcoin', models.TextField(max_length=5)),
                ('votes_total', models.IntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvote_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
